choco install -y conemu
choco install -y python2
choco install -y vim
choco install -y git
choco install -y unxutils
choco install -y poshgit
choco install -y clink
choco install -y tortoisesvn
choco install -y tortoisegit
choco install -y svn
choco install -y hosts.editor
choco install -y filezilla
choco install -y winscp
choco install -y xmlstarlet
choco install -y sublimetext3
choco install -y 7zip
